### PR TITLE
[Issue 100] Added @oclif/plugin-update

### LINKED ISSUE #100: CLI: Add auto updater from oclif
https://oclif.io/docs/releasing#autoupdater

### PR DESCRIPTION
**Pull request by Tanner-Scadden**
## The Pull Request is ready

- [x] all github actions are passing
- [x] only a single issue was worked on
- [x] fixes #100
- [x] the branch follows the naming schema `issue-123-enable-x-does-not-disable-y`
- [x] the pull request has a sensible title

## Intention

With this change I intend to...
- Add the `@oclif/plugin-update` plugin. It also handles updating automatically for us.

## Review Points

Please take extra care reviewing...
- We need to add the s3 path in the package.json

## The code follows best practices

- [x] duplicate code has been extracted where possible
- [x] issues for follow-up tasks have been created
- [x] tests have been written for any new functionality
- [x] there is no `any` type used
- [x] texts have been checked for grammar and spelling issues

### CODE REVIEW

**Comment by Tanner-Scadden** [comment]
@rphovley You will need to add the s3 path in the package.json for this ticket.

**Review by rphovley — APPROVED** [review]

**Comment by rphovley** [comment]
We are distributing through npm to start, so there is no s3 path

**Comment by rphovley** [comment]
Looks like we may not be able to really take advantage of this plugin: https://github.com/oclif/plugin-update/issues/3

**Comment by Tanner-Scadden** [comment]
@rphovley Did I pull the trigger too fast? I can create a custom plugin if needed that runs similarly as what I just did on the front end.

**Comment by rphovley** [comment]
If you want to take a crack at that, feel free to. Probably not urgent yet. Seems like that could be fun to work on

**Comment by Tanner-Scadden** [comment]
Ya I'll take a swing at it

**Pull request merged**
