### PR TITLE
feature: setup security scanning

### PR DESCRIPTION
**Pull request by Idrinth**
## The Pull Request is ready

- [x] all github actions are passing
- [x] only a single issue was worked on
- [x] fixes #0
- [x] the branch follows the naming schema `issue-123-enable-x-does-not-disable-y`
- [x] the pull request has a sensible title

## Intention

With this change I intend to add some security scanning:
- cron job weekly
- on push to main
- on pull request to main

## Review Points

Please take extra care reviewing that the package.json requires node 14, we should likely update that both there and here to 20.

## The code follows best practices

- [x] duplicate code has been extracted where possible
- [x] issues for follow-up tasks have been created
- [x] tests have been written for any new functionality
- [x] there is no `any` type used
- [x] texts have been checked for grammar and spelling issues

## Notes

This is a basic setup without any advanced features and will only scan for security issues so far.

### CODE REVIEW

**Comment by rphovley** [comment]
We don't have the engine specified right now in the package.json but we should do that so everyone's environment lines up with the CI environment. And I agree, we should set that to Node 20.

**Review by rphovley — CHANGES_REQUESTED** [review]
We don't have the engine specified right now in the package.json but we should do that so everyone's environment lines up with the CI environment. And I agree, we should set that to Node 20.

**Comment by Idrinth** [comment]
@rphovley there seems to be a mismatch between package.json and package-lock.json. I will have a more detailed look tomorrow morning, but likely `npm install` is all it takes.

**Comment by rphovley** [comment]
@Idrinth  Thanks for digging in. That should be in plenty of time

**Review by rphovley — APPROVED** [review]

**Pull request merged**
