### PR TITLE
[Issue 40] - Time Layout

### LINKED ISSUE #40: App: Time missing parts of the figma design
Need to add the rest of the layout for the time according to the figma design. 

Screenshot 2024-07-27 at 2 23 39 AM
Screenshot 2024-07-27 at 2 23 53 AM

### PR DESCRIPTION
**Pull request by Tanner-Scadden**
## The Pull Request is ready

- [ ] all github actions are passing
- [x] only a single issue was worked on
- [x] fixes #40
- [x] the branch follows the naming schema `issue-123-enable-x-does-not-disable-y`
- [x] the pull request has a sensible title

## Intention

With this change, I intend to...
- Implement more of the Time layout to make it easier to plugin data when it is integrated.

## Review Points

Please take extra care reviewing...
- That my code is following the right standards. If it is, I'll keep going and clean up some of the smaller details I've skipped over at the moment.

## The code follows best practices

- [x] duplicate code has been extracted where possible
- [x] issues for follow-up tasks have been created
- [ ] tests have been written for any new functionality
- [x] there is no `any` type used
- [ ] texts have been checked for grammar and spelling issues

## Notes
- Not sure what direction y'all want to do for the charts. Is there a specific charting library to use, should I just do some overlays on the progress components? 
- Hoping I am following the desired way of styling. Wasn't sure if we do one component per file either, and if I should be making a folder for the Time components IE `/src/components/Home/Time`.

### Images
Screenshot 2024-07-27 at 2 32 44 AM
Screenshot 2024-07-27 at 2 32 54 AM

### CODE REVIEW

**Comment by rphovley** [comment]
@danzjamz worked on the backend for this and will wire it up

**Review by rphovley — CHANGES_REQUESTED** [review]
Generally, we'll be doing a component per file

**Comment by rphovley** [comment]
Looks good! I haven't used Grid2 much because it's from the "unstable" package from mui. Have they landed on their new grid or?

**Comment by Tanner-Scadden** [comment]
> Looks good! I haven't used Grid2 much because it's from the "unstable" package from mui. Have they landed on their new grid or?

According to their [initial blog post](https://next.mui.com/blog/build-layouts-faster-with-grid-v2/), Grid2 is moving to stable in V6. I don't see any recent issues around it, either. I am not a big fan of V1 Grid, but I am happy to change it to using V1 if we want to roll with it for now and upgrade later! 

> Generally, we'll be doing a component per file

Do you prefer folders per component scope, or flat files unless it is for another route?

**Comment by rphovley** [comment]
Related components into a folder together. The Time folder is great, just split the component into multiple files in that folder

**Comment by rphovley** [comment]
Related components into a folder together. The Time folder is great, just split the component into multiple files in that folder

**Comment by rphovley** [comment]
How long until v6 mui?

**Comment by rphovley** [comment]
Looks like Q2 2024. If that's the case, we should just use Grid2 since V6 is right around the corner

**Review by rphovley — APPROVED** [review]

**Pull request merged**
