### PR TITLE
[Issue 47] CLI: Start Port in use & Process Name running detection

### LINKED ISSUE #47: CLI: handle existing running codeclimbers on start command
If you run npm exec codeclimbers start after the server is already running, the port will be in use and we need to provide better handling. 

To start, let's just log out a message to the user telling them "the codeclimbers server is already up on port: x with process id: "

### PR DESCRIPTION
**Pull request by Tanner-Scadden**
## The Pull Request is ready

- [ ] all github actions are passing
- [x] only a single issue was worked on
- [x] fixes #47 
- [x] the branch follows the naming schema `issue-123-enable-x-does-not-disable-y`
- [x] the pull request has a sensible title

## Intention

With this change I intend to...

On CLI start we can now:
- Detect if port is already in use and provide information on the process
- Detect if a code climbers server is already running 

## Review Points

Please take extra care reviewing...

- [Library I pulled in](https://www.npmjs.com/package/find-process) to help with it since I couldn't find much on how to do it without a lib in node. 

## The code follows best practices

- [x] duplicate code has been extracted where possible
- [x] issues for follow-up tasks have been created
- [x] tests have been written for any new functionality
- [ ] there is no `any` type used
- [x] texts have been checked for grammar and spelling issues

## Notes

Screenshot 2024-07-27 at 7 24 25 PM

### CODE REVIEW

**Comment by Tanner-Scadden** [comment]
@rphovley What are your thoughts on us detecting the server by using the process name instead of port? Or, it could even be enhanced so we check if the process name is the codeclimbers one, or if it is an external process? 

Implemented checking by name and setting the process name in this PR: https://github.com/CodeClimbersIO/cli/pull/50

**Comment by rphovley** [comment]
@Tanner-Scadden yeah, I like that better

**Review by rphovley — DISMISSED** [review]

**Comment by Tanner-Scadden** [comment]
@rphovley Awesome, pulled in #50 and added a check by process name as well.

**Review by rphovley — APPROVED** [review]
Looks good!

**Pull request merged**
